# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Ve0dhgFIEglghh_KwRwEzf-SGjXMAuo
"""

import pandas as pd


class TabelaFipe():
    def __init__(self) -> None:
        self.df=pd.read_excel('./zap.xlsx')
        self.df.to_csv('./FIPE.csv', index=False)
        self.fileCSV = pd.read_csv('./FIPE.csv')

    def qtdElementos(self):
        return len(self.df)

    def separacaocolumns(self):
        duas_colunas = self.df[['Índice FipeZAP']]
        tres_colunas=self.df['Imóveis residenciais']
        return duas_colunas, tres_colunas




tabela = TabelaFipe()
print("Quantidade de elementos:", tabela.qtdElementos())
print("Coluna data: ", tabela.separacaocolumns())